export const LOGOS = [
    { src: "/images/Stack/Airbyte.svg", name: "Airbyte" },
    { src: "/images/Stack/Anthropic.svg", name: "Anthropic" },
    { src: "/images/Stack/Azure.svg", name: "Azure" },
    { src: "/images/Stack/Bing.svg", name: "Bing" },
    { src: "/images/Stack/Composio.svg", name: "Composio" },
    { src: "/images/Stack/Confluence.svg", name: "Confluence" },
    { src: "/images/Stack/Couchbase.svg", name: "Couchbase" },
    { src: "/images/Stack/Evernote.svg", name: "Evernote" },
    { src: "/images/Stack/Github.svg", name: "Github" },
    { src: "/images/Stack/Glean.svg", name: "Glean" },
    { src: "/images/Stack/Gmail.svg", name: "Gmail" },
    { src: "/images/Stack/Google Cloud.svg", name: "Google Cloud" },
    { src: "/images/Stack/Google Drive.svg", name: "Google Drive" },
    { src: "/images/Stack/Groq.svg", name: "Groq" },
    { src: "/images/Stack/supa.svg", name: "Supa" },
    { src: "/images/Stack/Hugging Face.svg", name: "HuggingFace" },
    { src: "/images/Stack/LANGCHAIN.svg", name: "Langchain" },
    { src: "/images/Stack/Meta.svg", name: "Meta" },
    { src: "/images/Stack/Reddis.svg", name: "Reddis" },
    { src: "/images/Stack/MILVUS.svg", name: "Milvus" },
    { src: "/images/Stack/mistral-ai_wordmark 1.svg", name: "Mistral" },
    { src: "/images/Stack/MongoDB.svg", name: "MongoDB" },
    { src: "/images/Stack/Notion.svg", name: "Notion" },
    { src: "/images/Stack/NVIDIA.svg", name: "NVIDIA" },
    { src: "/images/Stack/Ollama.svg", name: "Ollama" },
    { src: "/images/Stack/Perplexity.svg", name: "Perplexity" },
    { src: "/images/Stack/Weaviate.svg", name: "Weaviate" },
    { src: "/images/Stack/Serper.svg", name: "Serper" },
    { src: "/images/Stack/Qdrant.svg", name: "Qdrant" },
    { src: "/images/Stack/Serp API.svg", name: "Serp API" },
    { src: "/images/Stack/Slack.svg", name: "Slack" },
    { src: "/images/Stack/supa.svg", name: "Supa" },
    { src: "/images/Stack/datastax.svg", name: "Datastax" },
    { src: "/images/Stack/Amazon.svg", name: "Amazon Bedrock" },
    { src: "/images/Stack/Tavily.svg", name: "Tavily" },
    { src: "/images/Stack/Upstash.svg", name: "Upstash" },
    { src: "/images/Stack/Vectara.svg", name: "Vectara" },
    { src: "/images/Stack/Wikipedia.svg", name: "Wikipedia" },
    { src: "/images/Stack/Wolfram Alpha.svg", name: "Wolfram Alpha" },
    { src: "/images/Stack/Yahoo Finance.svg", name: "Yahoo! Finance" },
    { src: "/images/Stack/zap.svg", name: "Zap" },
    { src: "/images/Stack/MeriTalk.svg", name: "MeriTalk" },
    { src: "/images/Stack/Pinecone.svg", name: "Pinecone" },
    { src: "/images/Stack/surface1.svg", name: "Cassandra" },
    { src: "/images/Stack/Unstructured.svg", name: "Unstructured" },
    { src: "/images/Stack/OpenAI.svg", name: "OpenAI" },
    { src: "/images/Stack/Crew.svg", name: "Crew AI" },
  ];